Added channels, changed orders to keep the same hierarchy the server has, modified the readme's and obsolete channel descriptions, added graven to reférents lists
GravenDev/ServeurDiscord pull request #14
Opened 2022-11-04 14:56 UTC by SkyrixFr

This commit is nearly a complete overhaul of this repository.
- Added channels : roles, questions-fréquentes, anciennes-vidéos, clash of code, dart | flutter

- Changed the orders of the different channels to keep the same hierarchy since new channels were added, example: 
the channel `annonces` was number two and became number 4 because of the channels `roles` and `questions-fréquentes`

- Added the new channels to the readme's

- Modified some obsolete descriptions of channels (like the `autres` channel that doesn't exist anymore because it is now a forum) Deleted some channels that don't exist/are not visible anymore

- Added Graven in the référents lists (like `applications-mobiles` and `dart | flutter`)

Good luck reviewing everything 😉

2022-11-04 20:05 UTC, g-clems requested changes

2022-11-04 20:05 UTC, g-clems commented on channels/1 - Système/2_roles.md
> +Ce salon contient un système de
Description incomplète

2022-11-04 20:05 UTC, g-clems commented on channels/4 - Salons d'aide/16_autres.md
> +Le salon `#❔︱autre︱other` est un forum vous permettant de poser vos questions, sur les
virgule en trop

2022-11-04 20:05 UTC, g-clems commented on channels/4 - Salons d'aide/16_autres.md
Guidelines manquante

2022-11-05 13:31 UTC, SkyrixFr commented on channels/4 - Salons d'aide/16_autres.md
Qu'est ce qu'une guideline?

2022-11-05 13:32 UTC, SkyrixFr commented on channels/4 - Salons d'aide/16_autres.md
C'est d'expliquer comment on ouvre un post?

2022-11-05 13:33 UTC, SkyrixFr commented on channels/1 - Système/2_roles.md
> +Ce salon contient un système de
```suggestion
Ce salon contient un système de rôles permettant aux utilisateurs de définir les languages pratiqué par les membres du serveur
```

2022-11-05 14:06 UTC, g-clems commented on channels/4 - Salons d'aide/16_autres.md
Elles sont visible en cliquant sur "nouveau post"

2022-11-05 14:17 UTC, SkyrixFr commented
All the changes asked were made and more was done (things I forgot to add in the old commit)

2022-11-05 15:13 UTC, g-clems approved these changes

2022-11-05 16:51 UTC, RedsTom approved these changes

2022-11-05 16:51 UTC, merged